### ISSUE TITLE
THEIA not only over France

### ISSUE THREAD

**Issue by olivierhagolle** [Fernerkundung/awesome-sentinel#4]
Hi Kersten,

THeia's production has been recently extended over different regions, may I suggest to replace this:
"Theia (Sentinel-2) tiles covering France only, athmospherically corrected L2A"

"Theia (Sentinel-2) tiles atmospherically corrected to L2A over selected regions including France, Belgium Burkina-Faso, Tunisia, Morocco..., "
(I also removed an h in atmospherically ;) )

And also:

Regarding the data mirrors, I do not think they are all global.
The French German and British are, but the others, I don't think so.

Anyway, thanks a lot for this useful resource page.
Best regards,
Olivier

**Comment by kr-stn** [comment]
Is there a systematic plan of the areas Theia is going to cover in the future? If not I'd change it to 

> atmospherically corrected L2A tiles covering mainly France

since my understanding of Theia is that you are aiming for full coverage over France?

Regarding the mirrors: I know that most are not trying to include full coverage (spatial as well as temporal). Unfortunately most do not publish exact roadplans of their plans - so I did not include this information into the 'Data Hubs and National Mirrors' section.

**Comment by olivierhagolle** [comment]
Hi Kersten
Theia is aiming at distributing data needed by French scientists, even if anyone can use them. A call was issued to select zones that cover 10 times  the surface of France. The selected zones are described here : 

http://www.cesbio.ups-tlse.fr/multitemp/?page_id=7501

Up to  now, we have processed only a small part of these zones, but we are adding new ones progressively. CNES has installed a new cluster, but it is having performance issues these days. We are much slower that what was designed, but hope it will improve soon.

Best regards,
Olivier

**Comment by kr-stn** [comment]
Thanks for the link and the map to the proposed areas. I included them in the [latest commit](https://github.com/Fernerkundung/awesome-sentinel/commit/34ae4fdf5a191e9babf60a6598caede7db15df3e).
